name: helpert_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  animate_do: ^2.1.0
  animated_bottom_navigation_bar: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  bot_toast: ^4.0.1
  fluttertoast: ^8.0.9
  camera: ^0.10.0+4
  path_provider: ^2.0.10
  path: ^1.8.0
  readmore: ^2.2.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.13
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_dynamic_links: ^5.0.3
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^12.0.3
  preload_page_view:
  google_sign_in: ^5.3.0
  image_picker: ^0.8.5+2
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  uuid: ^3.0.6
  flutter_switch: ^0.3.2
  linkedin_login: ^2.2.1
  table_calendar: ^3.0.6
  video_compress: ^3.1.0
  image_cropper: ^3.0.1
  equatable:
  sliver_tools: ^0.2.7
  visibility_detector:
  flutter_cache_manager: ^3.3.0
  share: ^2.0.4
  better_player:
  light_compressor:

  # agora rtc engine
  agora_rtc_engine: ^5.3.0
  flutter_ringtone_player: ^3.2.0
  permission_handler: ^10.0.0
  cached_network_image: ^3.2.1
  flutter_image_compress: ^1.1.3
  http_parser: ^4.0.1
  percent_indicator: ^4.2.2
  flutter_callkit_incoming:


  # sockets
  socket_io_client: ^1.0.0
  flutter_native_timezone: ^2.0.0
  firebase_core_platform_interface: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/png/app-icon.png"


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/users_profile_png/
    - assets/images/svg/edit_profile_icons/
    - assets/images/png/
    - assets/images/png/payment_settings_icons/
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700


    - family: Museo
      fonts:
        - asset: assets/fonts/museo/MuseoSansCyrl.otf
          weight: 400
        - asset: assets/fonts/museo/MuseoSansCyrl.otf
          weight: 500
        - asset: assets/fonts/museo/MuseoSansCyrl.otf
          weight: 600
        - asset: assets/fonts/museo/MuseoSansCyrl.otf
          weight: 700

    - family: proxima
      fonts:
        - asset: assets/fonts/proxima/ProximaNovaFont.otf
          weight: 400
        - asset: assets/fonts/proxima/ProximaNovaFont.otf
          weight: 500
        - asset: assets/fonts/proxima/ProximaNovaFont.otf
          weight: 600
        - asset: assets/fonts/proxima/ProximaNovaFont.otf
          weight: 700

